typography_spectrum: 0.07581454
color:
  saturation: 0.5175439
  brandStrength: 0.4035088
  lightness: 0.5275689
  brandColors:
    - '#20D6F6'
    - '#FDFDFD'
    - '#8F8F8F'
    - '#010101'
    - '#404040'
  rhythmicContrast: 0.9022557
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6209273
analytics:
  twitter: null
  google: null
  facebook: null
name: pleasurealm
cta:
  bucket: null
  version: null
  domain: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: WE ARE PLEASUREALM
purpose: []
