name: pleasurealm
favicon: null
layout_spectrum: 0.2733698240481317
typography_spectrum: 0.7238583038561046
title: 'Pleasurealm website '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.026441387133672833
  lightness: 0.7000021317508072
  saturation: 0.9522414146922529
  rhythmicContrast: 0.0795954701025039
purpose: []
